# Generated by Django 4.2 on 2025-11-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                ("genre", models.CharField(max_length=100, verbose_name="Genre")),
                ("director", models.CharField(max_length=150, verbose_name="Director")),
                ("year", models.IntegerField(verbose_name="Year")),
                ("synopsis", models.TextField(verbose_name="Synopsis")),
            ],
            options={
                "verbose_name": "Movie",
                "verbose_name_plural": "Movies",
                "ordering": ["-year", "title"],
            },
        ),
    ]
