# Generated by Django 4.2 on 2025-11-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="synopsis",
            field=models.TextField(max_length=1000, verbose_name="Synopsis"),
        ),
    ]
